# Generated by Django 6.0.5 on 2026-05-13 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientprofile_consent_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, help_text='Users explicitly authorized to access this patient record.', related_name='authorized_patient_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
