# Generated by Django 6.0.5 on 2026-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditevent_correlation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('recommendation_created', 'Recommendation Created'), ('recommendation_updated', 'Recommendation Updated'), ('recommendation_review_requested', 'Recommendation Review Requested'), ('ai_provider_requested', 'AI Provider Requested'), ('review_submitted', 'Review Submitted'), ('review_approved', 'Review Approved'), ('review_overridden', 'Review Overridden'), ('review_rejected', 'Review Rejected')], max_length=50),
        ),
    ]
